### PR TITLE
Update PIO FIFO writes to new type-restricted API

### PR DESCRIPTION
**Pull request by 9names**
https://github.com/rp-rs/rp-hal/pull/318 changes the API for writing to the PIO FIFO to using explicit unsigned-integer types.
This PR should preserve the existing functionality with the new API.

I'm not sure how we're going to make CI happy with this change, to be honest. Maybe we'll need to disable examples in the HAL that use i2c-pio to go through the upgrade?

Maybe we should just bite the bullet and ship stable PIO drivers like this as part of the HAL?

### CODE REVIEW

**Comment by jannic** [comment]
One way to make CI happy would be to do it in multiple steps:
1) add the new methods write_u8_replicated, write_u16_replicated
2) change i2c-pio-rs (and others, if any) to use the new methods
3) change `write<T>(&mut self, value: T)` to `write(&mut self, value: u32)`

**Comment by 9names** [comment]
Yeah, that will work. A little bit of juggling but less trouble than having to mess with examples
I'll do that, thanks for the suggestion @jannic

**Comment by jannic** [comment]
After thinking about this a little bit more, I wonder if it would be better to just move the example to the i2c-pio-rs repository. After all, it's not really an example demonstrating the capabilities of the HAL, but of the i2c-pio implementation.
(And at it's current location, `rp-hal/boards/rp-pico/examples/pico_i2c_pio.rs`, it's difficult to find for users of other RP2040 based boards, even though the example is not really pico specific.)

**Comment by ithinuel** [comment]
That makes sense, I don't have strong opinions about that to be honest.
I imagine the same applies to [ws2812-pio](https://github.com/ithinuel/ws2812-pio-rs/), but a several boards do implement an example for this one though.

Would a link from the readme here to `rp-hal/boards/rp-pico/examples/pico_i2c_pio.rs` be enough to signpost users looking for an example while staying consistent with other PIO examples?

**Comment by jannic** [comment]
ws2812-pio is a little bit more tricky, indeed. It's not just the number of examples. One could argue that they are mostly duplicates and a single example in the ws2812-pio crate would be as good.
But there are many boards which do contain ws2812 based LEDs, and I think an example on how to access on-board peripherals is a good thing to have next to the board crate. And AFAIK ws2812-pio is just the best way to control these LEDs when using an rp2040. Not sure how to proceed with that one.

For i2c-pio the situation is different: Most users, particularly ones needing those examples, should probably go with the hardware i2c peripheral. i2c-pio is a nice example on what's possible with PIO, and for sure has use cases where the native i2c pins have limitations, but that's more advanced stuff and doesn't need to be available next to the board crates.

Regarding the link: If we move the example, https://github.com/rp-rs/pio-rs#pio-examples should be updated to point directly to i2c-pio. And a link directly from https://github.com/rp-rs/rp-hal would be nice as well. As long as it's only this one example, the link could be placed directly in https://github.com/rp-rs/rp-hal#getting-started where the pio-rs is mentioned. Once we have more examples to refer to, a separate section would be better.

**Comment by 9names** [comment]
ws2812 is tough because basically no-one put them on the same pins as SPI MOSI, so PIO or bit-banging are our only options - I don't want to use bit-banging :(

**Comment by jannic** [comment]
Let's not worry too much about ws2812: It's not a blocker for this issue.
Neither is the location of the i2c-pio example, as @9names already applied https://github.com/rp-rs/rp-hal/pull/318/commits/fc3e2dfee1fd62ac6fe0915cfc1cad9000097da4 to the rp-hal PR.

**Comment by 9names** [comment]
This was integrated into #8, closing now

**Pull request closed without merging**
